export const ALL_PERMISSIONS = [
  { key: 'dashboard',         label: 'Dashboard' },
  { key: 'envio-rapido',      label: 'Envio Rápido' },
  { key: 'brinks',            label: 'Depósitos Brinks' },
  { key: 'manuais',           label: 'Depósitos Manuais' },
  { key: 'resumo',            label: 'Resumo Diário / CAIXAS' },
  { key: 'extrato',           label: 'Extrato Bancário' },
  { key: 'alvaras',           label: 'Alvarás e Licenças' },
  { key: 'garantias',         label: 'Notas e Garantias' },
  { key: 'docs-empresa',      label: 'Documentos da Empresa' },
  { key: 'postos',            label: 'Postos' },
  { key: 'usuarios',          label: 'Usuários' },
  { key: 'bancos',            label: 'Contas Bancárias' },
  { key: 'pessoal',           label: 'Pessoal' },
  { key: 'recrutamento',      label: 'Recrutamento' },
  { key: 'lancamento-notas',      label: 'Lançamento de Notas' },
  { key: 'pedidos-compra',        label: 'Pedidos de Compra' },
  { key: 'cursos-treinamentos',   label: 'Cursos e Treinamentos' },
  { key: 'configuracoes',         label: 'Configurações' },
  { key: 'acessos-senhas',        label: 'Acessos e Senhas' },
  { key: 'contabilidade',         label: 'Contabilidade' },
  { key: 'identidade-visual',     label: 'Identidade Visual e Modelos' },
  { key: 'historico-rede',        label: 'Histórico da Rede (todos os postos)' },
  { key: 'caixa-entrada',         label: 'Caixa de Entrada (Currículos e Feedback)' },
  { key: 'almoxarifado',          label: 'Almoxarifado (Patrimônio)' },
  { key: 'chamados',              label: 'Chamados de Manutenção' },
  { key: 'conciliacao-pix',       label: 'Conciliação Pix' },
  { key: 'cartoes-importar',      label: 'Cartões – Importar Vendas' },
  { key: 'cartoes-a-receber',     label: 'Cartões – A Receber' },
  { key: 'cartoes-vendas',        label: 'Cartões – Vendas Importadas' },
  { key: 'cartoes-excluir',       label: 'Cartões – Excluir Vendas' },
  { key: 'cartoes-conferencia',   label: 'Cartões – Conferência por Turno' },
  { key: 'trancar-caixa',         label: 'Trancar Caixa' },
] as const;

export type PermissionKey = (typeof ALL_PERMISSIONS)[number]['key'];

export const PROFILE_PRESETS: Record<string, string[]> = {
  master:    ALL_PERMISSIONS.map((p) => p.key),
  admin:     ALL_PERMISSIONS.map((p) => p.key).filter((k) => k !== 'trancar-caixa'),
  gerente:   ['envio-rapido', 'brinks', 'manuais', 'resumo', 'pessoal', 'alvaras', 'garantias', 'docs-empresa', 'pedidos-compra', 'almoxarifado', 'chamados'],
  frentista: ['envio-rapido'],
};

// Priority order for "first allowed page" redirect
export const ROUTE_PERMISSION_MAP: { path: string; permission: string }[] = [
  { path: '/',           permission: 'dashboard' },
  { path: '/envio-rapido', permission: 'envio-rapido' },
  { path: '/brinks',     permission: 'brinks' },
  { path: '/manuais',    permission: 'manuais' },
  { path: '/resumo',     permission: 'resumo' },
  { path: '/extrato',    permission: 'extrato' },
  { path: '/alvaras',       permission: 'alvaras' },
  { path: '/garantias',     permission: 'garantias' },
  { path: '/docs-empresa',  permission: 'docs-empresa' },
  { path: '/postos',     permission: 'postos' },
  { path: '/usuarios',   permission: 'usuarios' },
  { path: '/bancos',     permission: 'bancos' },
  { path: '/funcionarios',      permission: 'pessoal' },
  { path: '/ponto',             permission: 'pessoal' },
  { path: '/fechamento',        permission: 'pessoal' },
  { path: '/historico-pessoal', permission: 'pessoal' },
  { path: '/recrutamento',      permission: 'recrutamento' },
  { path: '/compras/pedidos',    permission: 'pedidos-compra' },
  { path: '/compras/notas',     permission: 'lancamento-notas' },
  { path: '/cursos',            permission: 'cursos-treinamentos' },
  { path: '/configuracoes',    permission: 'configuracoes' },
  { path: '/acessos-senhas',   permission: 'acessos-senhas' },
  { path: '/contabilidade',      permission: 'contabilidade' },
  { path: '/identidade-visual',  permission: 'identidade-visual' },
  { path: '/caixa-entrada',    permission: 'caixa-entrada' },
  { path: '/almoxarifado',          permission: 'almoxarifado' },
  { path: '/manutencao/chamados',   permission: 'chamados' },
  { path: '/financeiro/conciliacao-pix',      permission: 'conciliacao-pix' },
  { path: '/financeiro/cartoes', permission: 'cartoes-importar' },
];

export function firstAllowedPath(hasPermission: (k: string) => boolean): string {
  return ROUTE_PERMISSION_MAP.find((r) => hasPermission(r.permission))?.path ?? '/login';
}
